### PR TITLE
fix inconsistent DCpath for Slayer

### PR DESCRIPTION
**Pull request by SylvanSign**
I was playing around with your data file and the images from the dc repo, and I stumbled upon this inconsistency

### CODE REVIEW

**Comment by rezwits** [comment]
Hey no problem, thanks.  As far as the data file, that's usually kept on the table branch which I work from until a merge.  I DID tho, update the main database that generates the json.  There is an update coming in week, i.e. before next Saturday.  And the change is made.  Thanks again!

**Comment by SylvanSign** [comment]
Thanks, @rezwits ! First of all, thank you so much for your work on Cardnum! Secondly, I've got a couple questions:

So this database is the source of truth then? How is that db maintained over time?

I'm interested in developing some MECCG tooling, mostly as a way for me to practice some new programming ideas, and I would love to be able to import the card data and card images at least. Does it make sense for me to reference this fdata directory and the dc repo for those things respectively? Or do you recommend something else?

**Comment by rezwits** [comment]
Awesome and thanks.  The main reasons why this project was created was:

1.  gccg was getting old, used since 2003, I believe and didn't change much.
2. gccg was really slow even on fast hardware.
3. gccg was hard for some to install using nix commands
4. gccg was referencing some 32-bit libraries, that newer versions of macOS would make obsolete
5. People wanted to play and I knew they did, but couldn't
6. I also felt via web browser, for future chromebook clients, would be great
7. I too needed a platform that I could really get into and keep. my skills polished.
8. Basic HTML and JS projects don't really get me excited like html/js via clojure does!
9. I was also hoping to get some people interested in open source by hust doing individual card logic if anything
10. The docker is really easy for people to get started with just a simple text editor if they want
11. There is a problem with docker and the project right now, the ERRATUM fetching is not implemented fully
12. The db is a FileMaker database I have been infusing, tooling, and juicing since 2005.
13. Currently, I have many backups of it, but there is access via a web tool for the dreamcard team, to edit data
14. That fdata directory is essentially the source of truth for the project, the fetch data
15. The FMPDB is mainly for us to create new cards and act like netrunnerdb did/does for jinteki.net
16. But since we (meccg users) don't have a netrunnerdb, I had to come up with the fdata location.
17. Those images are the relics of a scan project long, long, ago that I have no idea who did.
18. They have been shared by many!
19. My site actually has images that I "polished" with some filters, to get a richer look (i.e. a darker curve)
20. Have fun and last year was a rough year for everyone, and development slowed down, I actually moved into a final place to dwell and I am really going to start jamming again.

**Comment by SylvanSign** [comment]
Thanks for all the details! I really appreciate your time and explanation!

**Pull request closed without merging**
